---
- name: Initialize Antidote plugins
  ansible.builtin.command:
    # Путь к antidote.zsh - в terminal_setup_antidote_init (vars/Darwin.yml или vars/Debian.yml)
    cmd: >
      zsh -c "source {{ terminal_setup_antidote_init }} &&
      antidote bundle
      < {{ [terminal_setup_config_dir, '.zsh_plugins.txt'] | path_join }}
      > {{ [terminal_setup_config_dir, '.zsh_plugins.zsh'] | path_join }}"
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  changed_when: true
