---
terminal_setup_zsh_plugins:
  - "ohmyzsh/ohmyzsh path:lib"             # Базовые функции zsh
  - "ohmyzsh/ohmyzsh path:plugins/git"     # Авто дополнения для git
  - "ohmyzsh/ohmyzsh path:plugins/ansible" # Авто дополнения для ansible
  - "ohmyzsh/ohmyzsh path:plugins/golang"  # Авто дополнения для go
  - "ohmyzsh/ohmyzsh path:plugins/python"  # Для функции pyclean, и алиаса py
  - "ohmyzsh/ohmyzsh path:plugins/pip"     # Авто дополнения для pip
  - "popstas/zsh-command-time"             # Выводит время выполнения команды
  - "ohmyzsh/ohmyzsh path:plugins/extract" # Удобный распаковщик архивов
  - "zsh-users/zsh-autosuggestions"        # Подсказка-отображение последней команды при вводе
  - "viasite-ansible/fzf-widgets"          # fzf виджеты
  - "zsh-users/zsh-completions"            # Набор скриптов автодополнения для современных утилит от сообщества
  - "zsh-users/zsh-syntax-highlighting"    # Подцветка синтаксиса команды (ДОЛЖЕН ПОДКЛЮЧАТЬСЯ ПОСЛЕДНИМ)
