- name: Remove the conflicting Homebrew Git completion script (macOS)
  ansible.builtin.file:
    path: /opt/homebrew/share/zsh/site-functions/_git
    state: absent
  when: ansible_os_family == 'Darwin'
