---
galaxy_info:
  author: waldemar13311 (https://github.com/waldemar13311)
  description: Base zsh setup
  company: Home lab

  license: AGPL-3.0-or-later

  min_ansible_version: "2.1"

  platforms:
    - name: MacOSX

  galaxy_tags:
    - macos
    - zsh
    - antidote
    - dotfiles
    - terminal
    - development
